<?php

namespace NajahHost\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

    public function getNbNotifications($userID)
    {
        $sql = 'SELECT n.id, n.tache_id, n.is_read
	                FROM notification n JOIN notification_user nu ON n.id = nu.notification_id WHERE nu.user_id = :userID  and n.is_read = false';

        $params = array('userID' => $userID);
        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();

    }
}
